/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import java.util.*;

public class AddressBookMain {
	public static void main(String[] args) {
		
		AddressBookList addressBookList = new AddressBookList();
		Scanner in = new Scanner(System.in);
		boolean b = false;
		System.out.println("Welcome");
		System.out.println("1. Open existing addressbook");
		System.out.println("2. Open new addressbook");
		System.out.println("3. Exit");
		int option = in.nextInt();
		while(option != 3) {
			if(option == 1)
				addressBookList.openAddressBook();
			else if(option == 2)
				addressBookList.newAddressBook();
			else if(option == 3)
				break;
			else{
	      		System.out.println("Error! Enter correct choice-");    
	      	}
	      	System.out.println("Enter choice again (1. Open existing addressbook, 2. Open new addressbook, 3. Exit)-");
	      	option = in.nextInt();
	      }
		System.out.println("Thank You !");
	}
}